#
# gcc makefile for AROS
#
# To start with we'll get it working without building the libraries

TARGET = Fred
FREDLIB = # frexxed.library

CC = gcc
AS = gcc -c

# Initial compile without PowerPacker or XPK support
CFLAGS = -g -Wall -c -unsigned-char -DFREXXED -DUSE_C_SCREEN_SETUP -DDEBUG -DLOG_FILE_EXECUTION -DAMIGA -Dtest -I ../../FPL/include/ -DNO_PPACKER -DNO_XPK -funsigned-char -D__AMIGADATE__="\"`date`\""
LDFLAGS= -lamiga
#-lreqtools 
ASMFLAGS = -c

include Rules.mk
