# Linux Makefile
#
# Note that a Linux port is *way* off. This is mostly testing at this stage

TARGET = Fred
FREDLIB = # frexxed.library

CC = gcc
AS = gcc -c
CFLAGS = -g -Wall -c -unsigned-char -DFREXXED -DUSE_C_SCREEN_SETUP -DDEBUG -DLOG_FILE_EXECUTION -Dtest
LDFLAGS=
ASMFLAGS = -c
LIBS =

include Rules.mk
